// List of available tables extracted from the KnessetOdataManual.docx
export const TABLES = [
  "KNS_Agenda",
  "KNS_Bill",
  "KNS_BillHistoryInitiator",
  "KNS_BillInitiator",
  "KNS_BillName",
  "KNS_BillSplit",
  "KNS_BillUnion",
  "KNS_CmtSessionItem",
  "KNS_CmtSiteCode",
  "KNS_Committee",
  "KNS_CommitteeSession",
  "KNS_BroadcastCommitteSession",
  "KNS_DocumentAgenda",
  "KNS_DocumentBill",
  "KNS_DocumentCommitteeSession",
  "KNS_DocumentIsraelLaw",
  "KNS_DocumentPlenumSession",
  "KNS_DocumentQuery",
  "KNS_DocumentSecondaryLaw",
  "KNS_Faction",
  "KNS_GovMinistry",
  "KNS_IsraelLaw",
  "KNS_IsraelLawBinding",
  "KNS_IsraelLawClassificiation",
  "KNS_IsraelLawMinistry",
  "KNS_IsraelLawName",
  "KNS_ItemType",
  "KNS_JointCommittee",
  "KNS_KnessetDates",
  "KNS_LawBinding",
  "KNS_MkSiteCode",
  "KNS_Person",
  "KNS_PersonToPosition",
  "KNS_PlenumSession",
  "KNS_PlmSessionItem",
  "KNS_Position",
  "KNS_Query",
  "KNS_SecLawAuthorizingLaw",
  "KNS_SecLawRegulator",
  "KNS_SecondaryLaw",
  "KNS_SecToSecBinding",
  "KNS_Status",
  "KNS_PlenumVote",
  "KNS_PlenumVoteResult",
];

// Detailed metadata for table fields (unchanged from previous version)
export const TABLE_FIELDS_METADATA = {
  KNS_Agenda: [
    { name: "Id", type: "Edm.Int32" },
    { name: "Number", type: "Edm.Int32" },
    { name: "ClassificationID", type: "Edm.Int32" },
    { name: "ClassificationDesc", type: "Edm.String" },
    { name: "LeadingAgendaID", type: "Edm.Int32" },
    { name: "KnessetNum", type: "Edm.Int32" },
    { name: "Name", type: "Edm.String" },
    { name: "SubTypeID", type: "Edm.Int32" },
    { name: "SubTypeDesc", type: "Edm.String" },
    { name: "StatusID", type: "Edm.Int32" },
    { name: "InitiatorPersonID", type: "Edm.Int32" },
    { name: "GovRecommendationID", type: "Edm.Int32" },
    { name: "GovRecommendationDesc", type: "Edm.String" },
    { name: "PresidentDecisionDate", type: "Edm.DateTimeOffset" },
    { name: "PostopenmentReasonID", type: "Edm.Int32" },
    { name: "PostopenmentReasonDesc", type: "Edm.String" },
    { name: "CommitteeID", type: "Edm.Int32" },
    { name: "RecommendCommitteeID", type: "Edm.Int32" },
    { name: "MinisterPersonID", type: "Edm.Int32" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_Bill: [
    { name: "Id", type: "Edm.Int32" },
    { name: "KnessetNum", type: "Edm.Int32" },
    { name: "Name", type: "Edm.String" },
    { name: "TypeID", type: "Edm.Int32" },
    { name: "TypeDesc", type: "Edm.String" },
    { name: "SubTypeID", type: "Edm.Int32" },
    { name: "SubTypeDesc", type: "Edm.String" },
    { name: "PrivateNumber", type: "Edm.Int32" },
    { name: "CommitteeID", type: "Edm.Int32" },
    { name: "StatusID", type: "Edm.Int32" },
    { name: "Number", type: "Edm.Int32" },
    { name: "PostponementReasonID", type: "Edm.Int32" },
    { name: "PostponementReasonDesc", type: "Edm.String" },
    { name: "PublicationDate", type: "Edm.DateTimeOffset" },
    { name: "PublicationSeriesID", type: "Edm.Int32" },
    { name: "PublicationSeriesDesc", type: "Edm.String" },
    { name: "PublicationSeriesFirstCallID", type: "Edm.Int32" },
    { name: "PublicationSeriesFirstCallDesc", type: "Edm.String" },
    { name: "MagazineNumber", type: "Edm.String" },
    { name: "PageNumber", type: "Edm.String" },
    { name: "IsContinuationBill", type: "Edm.Boolean" },
    { name: "SummaryLaw", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_BillHistoryInitiator: [
    { name: "Id", type: "Edm.Int32" },
    { name: "BillID", type: "Edm.Int32" },
    { name: "PersonID", type: "Edm.Int32" },
    { name: "IsInitiator", type: "Edm.Boolean" },
    { name: "StartDate", type: "Edm.DateTimeOffset" },
    { name: "EndDate", type: "Edm.DateTimeOffset" },
    { name: "ReasonID", type: "Edm.Int32" },
    { name: "ReasonDesc", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_BillInitiator: [
    { name: "Id", type: "Edm.Int32" },
    { name: "BillID", type: "Edm.Int32" },
    { name: "PersonID", type: "Edm.Int32" },
    { name: "IsInitiator", type: "Edm.Boolean" },
    { name: "Ordinal", type: "Edm.Int32" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_BillName: [
    { name: "Id", type: "Edm.Int32" },
    { name: "BillID", type: "Edm.Int32" },
    { name: "Name", type: "Edm.String" },
    { name: "NameHistoryTypeID", type: "Edm.Int32" },
    { name: "NameHistoryTypeDesc", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_BillSplit: [
    { name: "Id", type: "Edm.Int32" },
    { name: "MainBillID", type: "Edm.Int32" },
    { name: "SplitBillID", type: "Edm.Int32" },
    { name: "Name", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_BillUnion: [
    { name: "Id", type: "Edm.Int32" },
    { name: "MainBillID", type: "Edm.Int32" },
    { name: "UnionBillID", type: "Edm.Int32" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_CmtSessionItem: [
    { name: "Id", type: "Edm.Int32" },
    { name: "ItemID", type: "Edm.Int32" },
    { name: "CommitteeSessionID", type: "Edm.Int32" },
    { name: "Ordinal", type: "Edm.Int32" },
    { name: "StatusID", type: "Edm.Int32" },
    { name: "Name", type: "Edm.String" },
    { name: "ItemTypeID", type: "Edm.Int32" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_CmtSiteCode: [
    { name: "Id", type: "Edm.Int32" },
    { name: "KnsID", type: "Edm.Int32" },
    { name: "SiteId", type: "Edm.Int32" },
  ],
  KNS_Committee: [
    { name: "Id", type: "Edm.Int32" },
    { name: "Name", type: "Edm.String" },
    { name: "CategoryID", type: "Edm.Int16" },
    { name: "CategoryDesc", type: "Edm.String" },
    { name: "KnessetNum", type: "Edm.Int32" },
    { name: "CommitteeTypeID", type: "Edm.Int32" },
    { name: "CommitteeTypeDesc", type: "Edm.String" },
    { name: "Email", type: "Edm.String" },
    { name: "StartDate", type: "Edm.DateTimeOffset" },
    { name: "FinishDate", type: "Edm.DateTimeOffset" },
    { name: "AdditionalTypeID", type: "Edm.Int32" },
    { name: "AdditionalTypeDesc", type: "Edm.String" },
    { name: "ParentCommitteeID", type: "Edm.Int32" },
    { name: "CommitteeParentName", type: "Edm.String" },
    { name: "IsCurrent", type: "Edm.Boolean" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_CommitteeSession: [
    { name: "Id", type: "Edm.Int32" },
    { name: "Number", type: "Edm.Int32" },
    { name: "KnessetNum", type: "Edm.Int32" },
    { name: "TypeID", type: "Edm.Int32" },
    { name: "TypeDesc", type: "Edm.String" },
    { name: "CommitteeID", type: "Edm.Int32" },
    { name: "StatusID", type: "Edm.Int32" },
    { name: "StatusDesc", type: "Edm.String" },
    { name: "Location", type: "Edm.String" },
    { name: "SessionUrl", type: "Edm.String" },
    { name: "BroadcastUrl", type: "Edm.String" },
    { name: "StartDate", type: "Edm.DateTimeOffset" },
    { name: "FinishDate", type: "Edm.DateTimeOffset" },
    { name: "Note", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_BroadcastCommitteSession: [
    { name: "Id", type: "Edm.Int32" },
    { name: "BroadcastId", type: "Edm.Int32" },
    { name: "BroadcastUrl", type: "Edm.String" },
  ],
  KNS_DocumentAgenda: [
    { name: "Id", type: "Edm.Int32" },
    { name: "AgendaID", type: "Edm.Int32" },
    { name: "GroupTypeID", type: "Edm.Byte" },
    { name: "GroupTypeDesc", type: "Edm.String" },
    { name: "ApplicationID", type: "Edm.Byte" },
    { name: "ApplicationDesc", type: "Edm.String" },
    { name: "FilePath", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_DocumentBill: [
    { name: "Id", type: "Edm.Int32" },
    { name: "BillID", type: "Edm.Int32" },
    { name: "GroupTypeID", type: "Edm.Byte" },
    { name: "GroupTypeDesc", type: "Edm.String" },
    { name: "ApplicationID", type: "Edm.Byte" },
    { name: "ApplicationDesc", type: "Edm.String" },
    { name: "FilePath", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_DocumentCommitteeSession: [
    { name: "Id", type: "Edm.Int32" },
    { name: "CommitteeSessionID", type: "Edm.Int32" },
    { name: "GroupTypeID", type: "Edm.Byte" },
    { name: "GroupTypeDesc", type: "Edm.String" },
    { name: "ApplicationID", type: "Edm.Byte" },
    { name: "ApplicationDesc", type: "Edm.String" },
    { name: "FilePath", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_DocumentIsraelLaw: [
    { name: "Id", type: "Edm.Int32" },
    { name: "IsraelLawID", type: "Edm.Int32" },
    { name: "GroupTypeID", type: "Edm.Byte" },
    { name: "GroupTypeDesc", type: "Edm.String" },
    { name: "ApplicationID", type: "Edm.Byte" },
    { name: "ApplicationDesc", type: "Edm.String" },
    { name: "FilePath", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_DocumentPlenumSession: [
    { name: "Id", type: "Edm.Int32" },
    { name: "PlenumSessionID", type: "Edm.Int32" },
    { name: "GroupTypeID", type: "Edm.Byte" },
    { name: "GroupTypeDesc", type: "Edm.String" },
    { name: "ApplicationID", type: "Edm.Byte" },
    { name: "ApplicationDesc", type: "Edm.String" },
    { name: "FilePath", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_DocumentQuery: [
    { name: "Id", type: "Edm.Int32" },
    { name: "QueryID", type: "Edm.Int32" },
    { name: "GroupTypeID", type: "Edm.Byte" },
    { name: "GroupTypeDesc", type: "Edm.String" },
    { name: "ApplicationID", type: "Edm.Byte" },
    { name: "ApplicationDesc", type: "Edm.String" },
    { name: "FilePath", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_DocumentSecondaryLaw: [
    { name: "Id", type: "Edm.Int32" },
    { name: "SecondaryLawId", type: "Edm.Int32" },
    { name: "GroupTypeID", type: "Edm.Byte" },
    { name: "GroupTypeDesc", type: "Edm.String" },
    { name: "ApplicationID", type: "Edm.Byte" },
    { name: "ApplicationDesc", type: "Edm.String" },
    { name: "FilePath", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_Faction: [
    { name: "Id", type: "Edm.Int32" },
    { name: "Name", type: "Edm.String" },
    { name: "KnessetNum", type: "Edm.Int32" },
    { name: "StartDate", type: "Edm.DateTimeOffset" },
    { name: "FinishDate", type: "Edm.DateTimeOffset" },
    { name: "IsCurrent", type: "Edm.Boolean" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_GovMinistry: [
    { name: "Id", type: "Edm.Int32" },
    { name: "Name", type: "Edm.String" },
    { name: "IsActive", type: "Edm.Boolean" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_IsraelLaw: [
    { name: "Id", type: "Edm.Int32" },
    { name: "KnessetNum", type: "Edm.Int32" },
    { name: "Name", type: "Edm.String" },
    { name: "IsBasicLaw", type: "Edm.Boolean" },
    { name: "IsFavoriteLaw", type: "Edm.Boolean" },
    { name: "PublicationDate", type: "Edm.DateTimeOffset" },
    { name: "LatestPublicationDate", type: "Edm.DateTimeOffset" },
    { name: "IsBudgetLaw", type: "Edm.Boolean" },
    { name: "LawValidityID", type: "Edm.Int32" },
    { name: "LawValidityDesc", type: "Edm.String" },
    { name: "ValidityStartDate", type: "Edm.DateTimeOffset" },
    { name: "ValidityStartDateNotes", type: "Edm.String" },
    { name: "ValidityFinishDate", type: "Edm.DateTimeOffset" },
    { name: "ValidityFinishDateNotes", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_IsraelLawBinding: [
    { name: "Id", type: "Edm.Int32" },
    { name: "IsraelLawID", type: "Edm.Int32" },
    { name: "IsraelLawReplacedID", type: "Edm.Int32" },
    { name: "LawID", type: "Edm.Int32" },
    { name: "LawTypeID", type: "Edm.Int32" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_IsraelLawClassificiation: [
    { name: "Id", type: "Edm.Int32" },
    { name: "IsraelLawID", type: "Edm.Int32" },
    { name: "ClassificiationID", type: "Edm.Int32" },
    { name: "ClassificiationDesc", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_IsraelLawMinistry: [
    { name: "Id", type: "Edm.Int32" },
    { name: "IsraelLawID", type: "Edm.Int32" },
    { name: "GovMinistryID", type: "Edm.Int32" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_IsraelLawName: [
    { name: "Id", type: "Edm.Int32" },
    { name: "IsraelLawID", type: "Edm.Int32" },
    { name: "LawID", type: "Edm.Int32" },
    { name: "LawTypeID", type: "Edm.Int32" },
    { name: "Name", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_ItemType: [
    { name: "Id", type: "Edm.Int32" },
    { name: "Desc", type: "Edm.String" },
    { name: "TableName", type: "Edm.String" },
  ],
  KNS_JointCommittee: [
    { name: "Id", type: "Edm.Int32" },
    { name: "CommitteeID", type: "Edm.Int32" },
    { name: "ParticipantCommitteeID", type: "Edm.Int32" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_KnessetDates: [
    { name: "Id", type: "Edm.Int32" },
    { name: "KnessetNum", type: "Edm.Int32" },
    { name: "Name", type: "Edm.String" },
    { name: "Assembly", type: "Edm.Int32" },
    { name: "Plenum", type: "Edm.Int32" },
    { name: "PlenumStart", type: "Edm.DateTimeOffset" },
    { name: "PlenumFinish", type: "Edm.DateTimeOffset" },
    { name: "IsCurrent", type: "Edm.Boolean" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_LawBinding: [
    { name: "Id", type: "Edm.Int32" },
    { name: "LawID", type: "Edm.Int32" },
    { name: "IsraelLawID", type: "Edm.Int32" },
    { name: "ParentLawID", type: "Edm.Int32" },
    { name: "LawTypeID", type: "Edm.Int32" },
    { name: "LawParentTypeID", type: "Edm.Int32" },
    { name: "BindingType", type: "Edm.Int32" },
    { name: "BindingTypeDesc", type: "Edm.String" },
    { name: "PageNumber", type: "Edm.String" },
    { name: "AmendmentType", type: "Edm.Int32" },
    { name: "AmendmentTypeDesc", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_MkSiteCode: [
    { name: "Id", type: "Edm.Int32" },
    { name: "KnsID", type: "Edm.Int32" },
    { name: "SiteId", type: "Edm.Int32" },
  ],
  KNS_Person: [
    { name: "Id", type: "Edm.Int32" },
    { name: "LastName", type: "Edm.String" },
    { name: "FirstName", type: "Edm.String" },
    { name: "GenderID", type: "Edm.Int32" },
    { name: "GenderDesc", type: "Edm.String" },
    { name: "Email", type: "Edm.String" },
    { name: "IsCurrent", type: "Edm.Boolean" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_PersonToPosition: [
    { name: "Id", type: "Edm.Int32" },
    { name: "PersonID", type: "Edm.Int32" },
    { name: "PositionID", type: "Edm.Int32" },
    { name: "KnessetNum", type: "Edm.Int32" },
    { name: "StartDate", type: "Edm.DateTimeOffset" },
    { name: "FinishDate", type: "Edm.DateTimeOffset" },
    { name: "GovMinistryID", type: "Edm.Int32" },
    { name: "GovMinistryName", type: "Edm.String" },
    { name: "DutyDesc", type: "Edm.String" },
    { name: "FactionID", type: "Edm.Int32" },
    { name: "FactionName", type: "Edm.String" },
    { name: "GovernmentNum", type: "Edm.Int32" },
    { name: "CommitteeID", type: "Edm.Int32" },
    { name: "CommitteeName", type: "Edm.String" },
    { name: "IsCurrent", type: "Edm.Boolean" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_PlenumSession: [
    { name: "Id", type: "Edm.Int32" },
    { name: "Number", type: "Edm.Int32" },
    { name: "KnessetNum", type: "Edm.Int32" },
    { name: "Name", type: "Edm.String" },
    { name: "StartDate", type: "Edm.DateTimeOffset" },
    { name: "FinishDate", type: "Edm.DateTimeOffset" },
    { name: "IsSpecialMeeting", type: "Edm.Boolean" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_PlmSessionItem: [
    { name: "Id", type: "Edm.Int32" },
    { name: "ItemID", type: "Edm.Int32" },
    { name: "PlenumSessionID", type: "Edm.Int32" },
    { name: "ItemTypeID", type: "Edm.Int32" },
    { name: "ItemTypeDesc", type: "Edm.String" },
    { name: "Ordinal", type: "Edm.Int64" },
    { name: "Name", type: "Edm.String" },
    { name: "StatusID", type: "Edm.Int32" },
    { name: "IsDiscussion", type: "Edm.Int32" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_Position: [
    { name: "Id", type: "Edm.Int32" },
    { name: "Description", type: "Edm.String" },
    { name: "GenderID", type: "Edm.Int32" },
    { name: "GenderDesc", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_Query: [
    { name: "Id", type: "Edm.Int32" },
    { name: "Number", type: "Edm.Int32" },
    { name: "KnessetNum", type: "Edm.Int32" },
    { name: "Name", type: "Edm.String" },
    { name: "TypeID", type: "Edm.Int32" },
    { name: "TypeDesc", type: "Edm.String" },
    { name: "StatusID", type: "Edm.Int32" },
    { name: "PersonID", type: "Edm.Int32" },
    { name: "GovMinistryID", type: "Edm.Int32" },
    { name: "SubmitDate", type: "Edm.DateTimeOffset" },
    { name: "ReplyMinisterDate", type: "Edm.DateTimeOffset" },
    { name: "ReplyDatePlanned", type: "Edm.DateTimeOffset" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_SecLawAuthorizingLaw: [
    { name: "Id", type: "Edm.Int32" },
    { name: "AuthorizingLawID", type: "Edm.Int32" },
    { name: "SecondaryLawID", type: "Edm.Int32" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_SecLawRegulator: [
    { name: "Id", type: "Edm.Int32" },
    { name: "SecondaryLawID", type: "Edm.Int32" },
    { name: "RegulatorTypeID", type: "Edm.Int32" },
    { name: "RegulatorTypeDesc", type: "Edm.String" },
    { name: "RegulatorID", type: "Edm.Int32" },
    { name: "RegulatorDesc", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_SecondaryLaw: [
    { name: "Id", type: "Edm.Int32" },
    { name: "KnessetNum", type: "Edm.Int32" },
    { name: "Name", type: "Edm.String" },
    { name: "CompletionCauseID", type: "Edm.Int32" },
    { name: "CompletionCauseDesc", type: "Edm.String" },
    { name: "PostponementReasonID", type: "Edm.Int32" },
    { name: "PostponementReasonDesc", type: "Edm.String" },
    { name: "KnessetInvolvementID", type: "Edm.Int32" },
    { name: "KnessetInvolvementDesc", type: "Edm.String" },
    { name: "CommitteeID", type: "Edm.Int32" },
    { name: "PublicationSeriesID", type: "Edm.Int32" },
    { name: "PublicationSeriesDesc", type: "Edm.String" },
    { name: "MagazineNumber", type: "Edm.String" },
    { name: "PageNumber", type: "Edm.String" },
    { name: "PublicationDate", type: "Edm.DateTimeOffset" },
    { name: "MajorAuthorizingLawID", type: "Edm.Int32" },
    { name: "CommitteeReceivedDate", type: "Edm.DateTimeOffset" },
    { name: "CommitteeApprovalDate", type: "Edm.DateTimeOffset" },
    { name: "ApprovalDateWithoutDiscussion", type: "Edm.DateTimeOffset" },
    { name: "IsAmmendingLawOriginal", type: "Edm.Boolean" },
    { name: "ClassificationID", type: "Edm.Int32" },
    { name: "ClassificationDesc", type: "Edm.String" },
    { name: "IsEmergency", type: "Edm.Boolean" },
    { name: "SecretaryReceivedDate", type: "Edm.DateTimeOffset" },
    { name: "PlenumApprovalDate", type: "Edm.DateTimeOffset" },
    { name: "TypeID", type: "Edm.Int32" },
    { name: "TypeDesc", type: "Edm.String" },
    { name: "StatusID", type: "Edm.Int32" },
    { name: "StatusName", type: "Edm.String" },
    { name: "IsCurrent", type: "Edm.Boolean" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_SecToSecBinding: [
    { name: "Id", type: "Edm.Int32" },
    { name: "SecChildID", type: "Edm.Int32" },
    { name: "SecChildTypeID", type: "Edm.Int32" },
    { name: "SecParentID", type: "Edm.Int32" },
    { name: "SecParentTypeID", type: "Edm.Int32" },
    { name: "SecMainID", type: "Edm.Int32" },
    { name: "SecMainTypeID", type: "Edm.Int32" },
    { name: "BindingTypeID", type: "Edm.Int32" },
    { name: "BindingTypeDesc", type: "Edm.String" },
    { name: "IsTempLegislation", type: "Edm.Boolean" },
    { name: "IsSecondaryAmendment", type: "Edm.Boolean" },
    { name: "CorrectionNumber", type: "Edm.Int32" },
    { name: "AmendmentTypeID", type: "Edm.Int32" },
    { name: "AmendmentTypeDesc", type: "Edm.String" },
    { name: "ParagraphNumber", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_Status: [
    { name: "Id", type: "Edm.Int32" },
    { name: "Desc", type: "Edm.String" },
    { name: "TypeID", type: "Edm.Int32" },
    { name: "TypeDesc", type: "Edm.String" },
    { name: "OrderTransition", type: "Edm.Int32" },
    { name: "IsActive", type: "Edm.Boolean" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
  ],
  KNS_PlenumVote: [
    { name: "Id", type: "Edm.Int32" },
    { name: "VoteDateTime", type: "Edm.DateTimeOffset" },
    { name: "SessionID", type: "Edm.Int32" },
    { name: "ItemID", type: "Edm.Int32" },
    { name: "Ordinal", type: "Edm.Int32" },
    { name: "VoteMethodID", type: "Edm.Int32" },
    { name: "VoteMethodDesc", type: "Edm.String" },
    { name: "VoteStatusCode", type: "Edm.Int32" },
    { name: "VoteStatusDesc", type: "Edm.String" },
    { name: "VoteTitle", type: "Edm.String" },
    { name: "VoteSubject", type: "Edm.String" },
    { name: "IsNoConfidenceInGov", type: "Edm.Boolean" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
    { name: "ForOptionID", type: "Edm.Int32" },
    { name: "ForOptionDesc", type: "Edm.String" },
    { name: "AgainstOptionID", type: "Edm.Int32" },
    { name: "AgainstOptionDesc", type: "Edm.String" },
  ],
  KNS_PlenumVoteResult: [
    { name: "Id", type: "Edm.Int32" },
    { name: "MkId", type: "Edm.Int32" },
    { name: "VoteID", type: "Edm.Int32" },
    { name: "VoteDate", type: "Edm.DateTimeOffset" },
    { name: "ResultCode", type: "Edm.Int32" },
    { name: "ResultDesc", type: "Edm.String" },
    { name: "LastUpdatedDate", type: "Edm.DateTimeOffset" },
    { name: "LastName", type: "Edm.String" },
    { name: "FirstName", type: "Edm.String" },
  ],
};

// GENERATED FROM METADATA XML
export const TABLE_NAVIGATION_PROPERTIES_SUGGESTIONS = {
  KNS_Agenda: [
    { name: "KNS_DocumentAgenda", value: "KNS_DocumentAgenda" },
    { name: "KNS_Committee", value: "KNS_Committee" },
    { name: "KNS_PersonToPosition", value: "KNS_PersonToPosition" },
    { name: "KNS_Status", value: "KNS_Status" },
    { name: "KNS_RecommendCommittee", value: "KNS_RecommendCommittee" },
    {
      name: "KNS_PersonToPositionMinister",
      value: "KNS_PersonToPositionMinister",
    },
  ],
  KNS_Bill: [
    { name: "KNS_BillHistoryInitiator", value: "KNS_BillHistoryInitiator" },
    { name: "KNS_BillInitiator", value: "KNS_BillInitiator" },
    { name: "KNS_BillName", value: "KNS_BillName" },
    { name: "KNS_BillSplit", value: "KNS_BillSplit" },
    { name: "KNS_BillSplit_Main", value: "KNS_BillSplit_Main" },
    { name: "KNS_BillUnion", value: "KNS_BillUnion" },
    { name: "KNS_BillUnion_Main", value: "KNS_BillUnion_Main" },
    { name: "KNS_Committee", value: "KNS_Committee" },
    { name: "KNS_DocumentBill", value: "KNS_DocumentBill" },
    { name: "KNS_Status", value: "KNS_Status" },
    { name: "KNS_ItemType", value: "KNS_ItemType" },
  ],
  KNS_BillHistoryInitiator: [
    { name: "KNS_Bill", value: "KNS_Bill" },
    { name: "KNS_PersonToPosition", value: "KNS_PersonToPosition" },
  ],
  KNS_BillInitiator: [
    { name: "KNS_Bill", value: "KNS_Bill" },
    { name: "KNS_PersonToPosition", value: "KNS_PersonToPosition" },
  ],
  KNS_BillName: [{ name: "KNS_Bill", value: "KNS_Bill" }],
  KNS_BillSplit: [
    { name: "KNS_Bill", value: "KNS_Bill" },
    { name: "KNS_Bill_Main", value: "KNS_Bill_Main" },
  ],
  KNS_BillUnion: [
    { name: "KNS_Bill", value: "KNS_Bill" },
    { name: "KNS_Bill_Main", value: "KNS_Bill_Main" },
  ],
  KNS_CmtSessionItem: [
    { name: "KNS_CommitteeSession", value: "KNS_CommitteeSession" },
    { name: "KNS_Status", value: "KNS_Status" },
  ],
  KNS_Committee: [
    { name: "KNS_Bill", value: "KNS_Bill" },
    { name: "KNS_Agenda", value: "KNS_Agenda" },
    { name: "KNS_CommitteeSession", value: "KNS_CommitteeSession" },
    { name: "KNS_JointCommittee", value: "KNS_JointCommittee" },
    { name: "KNS_Agenda1", value: "KNS_Agenda1" },
    { name: "KNS_SecondaryLaw", value: "KNS_SecondaryLaw" },
    { name: "KNS_JointCommittee1", value: "KNS_JointCommittee1" },
  ],
  KNS_CommitteeSession: [
    { name: "KNS_Committee", value: "KNS_Committee" },
    {
      name: "KNS_DocumentCommitteeSession",
      value: "KNS_DocumentCommitteeSession",
    },
    { name: "KNS_Status", value: "KNS_Status" },
    { name: "KNS_CmtSessionItem", value: "KNS_CmtSessionItem" },
  ],
  KNS_DocumentAgenda: [{ name: "KNS_Agenda", value: "KNS_Agenda" }],
  KNS_DocumentBill: [{ name: "KNS_Bill", value: "KNS_Bill" }],
  KNS_DocumentCommitteeSession: [
    { name: "KNS_CommitteeSession", value: "KNS_CommitteeSession" },
  ],
  KNS_DocumentIsraelLaw: [{ name: "KNS_IsraelLaw", value: "KNS_IsraelLaw" }],
  KNS_DocumentPlenumSession: [
    { name: "KNS_PlenumSession", value: "KNS_PlenumSession" },
  ],
  KNS_DocumentQuery: [{ name: "KNS_Query", value: "KNS_Query" }],
  KNS_DocumentSecondaryLaw: [
    { name: "KNS_SecondaryLaw", value: "KNS_SecondaryLaw" },
  ],
  KNS_Faction: [
    { name: "KNS_PersonToPosition", value: "KNS_PersonToPosition" },
  ],
  KNS_GovMinistry: [
    { name: "KNS_Query", value: "KNS_Query" },
    { name: "KNS_PersonToPosition", value: "KNS_PersonToPosition" },
    { name: "KNS_IsraelLawMinistry", value: "KNS_IsraelLawMinistry" },
  ],
  KNS_IsraelLaw: [
    { name: "KNS_DocumentIsraelLaw", value: "KNS_DocumentIsraelLaw" },
    { name: "KNS_IsraelLawBinding", value: "KNS_IsraelLawBinding" },
    {
      name: "KNS_IsraelLawClassificiation",
      value: "KNS_IsraelLawClassificiation",
    },
    { name: "KNS_IsraelLawMinistry", value: "KNS_IsraelLawMinistry" },
    { name: "KNS_IsraelLawName", value: "KNS_IsraelLawName" },
  ],
  KNS_IsraelLawBinding: [{ name: "KNS_IsraelLaw", value: "KNS_IsraelLaw" }],
  KNS_IsraelLawClassificiation: [
    { name: "KNS_IsraelLaw", value: "KNS_IsraelLaw" },
  ],
  KNS_IsraelLawMinistry: [
    { name: "KNS_IsraelLaw", value: "KNS_IsraelLaw" },
    { name: "KNS_GovMinistry", value: "KNS_GovMinistry" },
  ],
  KNS_IsraelLawName: [{ name: "KNS_IsraelLaw", value: "KNS_IsraelLaw" }],
  KNS_ItemType: [{ name: "KNS_Bill", value: "KNS_Bill" }],
  KNS_JointCommittee: [
    { name: "KNS_Committee", value: "KNS_Committee" },
    { name: "KNS_CommitteeParticipant", value: "KNS_CommitteeParticipant" },
  ],
  KNS_Person: [
    { name: "KNS_PersonToPosition", value: "KNS_PersonToPosition" },
    { name: "KNS_PlenumVoteResult", value: "KNS_PlenumVoteResult" },
  ],
  KNS_PersonToPosition: [
    { name: "KNS_Faction", value: "KNS_Faction" },
    { name: "KNS_Person", value: "KNS_Person" },
    { name: "KNS_Agenda", value: "KNS_Agenda" },
    { name: "KNS_BillHistoryInitiator", value: "KNS_BillHistoryInitiator" },
    { name: "KNS_BillInitiator", value: "KNS_BillInitiator" },
    { name: "KNS_Agenda1", value: "KNS_Agenda1" },
    { name: "KNS_Position", value: "KNS_Position" },
    { name: "KNS_GovMinistry", value: "KNS_GovMinistry" },
  ],
  KNS_PlenumSession: [
    { name: "KNS_DocumentPlenumSession", value: "KNS_DocumentPlenumSession" },
    { name: "KNS_PlenumVote", value: "KNS_PlenumVote" },
    { name: "KNS_PlmSessionItem", value: "KNS_PlmSessionItem" },
  ],
  KNS_PlmSessionItem: [
    { name: "KNS_PlenumSession", value: "KNS_PlenumSession" },
    { name: "KNS_Status", value: "KNS_Status" },
  ],
  KNS_Position: [
    { name: "KNS_PersonToPosition", value: "KNS_PersonToPosition" },
  ],
  KNS_Query: [
    { name: "KNS_DocumentQuery", value: "KNS_DocumentQuery" },
    { name: "KNS_GovMinistry", value: "KNS_GovMinistry" },
    { name: "KNS_Status", value: "KNS_Status" },
  ],
  KNS_SecLawAuthorizingLaw: [
    { name: "KNS_SecondaryLaw", value: "KNS_SecondaryLaw" },
  ],
  KNS_SecLawRegulator: [
    { name: "KNS_SecondaryLaw", value: "KNS_SecondaryLaw" },
  ],
  KNS_SecondaryLaw: [
    { name: "KNS_SecToSecBinding", value: "KNS_SecToSecBinding" },
    { name: "KNS_SecToSecBinding_Parent", value: "KNS_SecToSecBinding_Parent" },
    { name: "KNS_Committee", value: "KNS_Committee" },
    { name: "KNS_Status", value: "KNS_Status" },
    { name: "KNS_SecLawAuthorizingLaw", value: "KNS_SecLawAuthorizingLaw" },
    { name: "KNS_SecLawRegulator", value: "KNS_SecLawRegulator" },
    { name: "KNS_DocumentSecondaryLaw", value: "KNS_DocumentSecondaryLaw" },
  ],
  KNS_SecToSecBinding: [
    { name: "KNS_SecondaryLaw", value: "KNS_SecondaryLaw" },
    { name: "KNS_SecondaryLaw_Parent", value: "KNS_SecondaryLaw_Parent" },
  ],
  KNS_Status: [
    { name: "KNS_Agenda", value: "KNS_Agenda" },
    { name: "KNS_Bill", value: "KNS_Bill" },
    { name: "KNS_CmtSessionItem", value: "KNS_CmtSessionItem" },
    { name: "KNS_CommitteeSession", value: "KNS_CommitteeSession" },
    { name: "KNS_PlmSessionItem", value: "KNS_PlmSessionItem" },
    { name: "KNS_Query", value: "KNS_Query" },
    { name: "KNS_SecondaryLaw", value: "KNS_SecondaryLaw" },
  ],
  KNS_PlenumVote: [{ name: "KNS_PlenumSession", value: "KNS_PlenumSession" }],
  KNS_PlenumVoteResult: [{ name: "KNS_Person", value: "KNS_Person" }],
  __GENERAL__: [
    { name: "Expand All (Caution!)", value: "*,*,*" }, // Placeholder, actual OData syntax for all is complex/service-specific
  ],
};
